Adjusts CGI harvester to use COSMIC search
ohsu-comp-bio/g2p-aggregator pull request #95
Opened 2018-03-03 00:34 UTC by mayfielg

CGI data lacked end coordinates, previously. This was due to parsing genomic information from the  'gDNA' field of the CGI file rather than checking for location information in COSMIC. 

This alters the CGI harvester to check for location information in COSMIC first; if no hits are returned, then the previous internal parsing function is used instead, with no changes the expectation that later in the harvest, checks against myvariant.info will grab the additional information.

2018-04-03 19:16 UTC, ahwagner commented
Does this PR conflict with #100?

2018-04-03 19:23 UTC, bwalsh commented
@mayfielg we should be targeting v0.10

2018-04-04 19:51 UTC, bwalsh requested changes
we should be targeting v0.10

2018-04-04 19:51 UTC, bwalsh commented on harvester/cgi_biomarkers.py
> +            sys.exit()
Should this exit be in the code?

2018-04-06 22:10 UTC, mayfielg commented
Moved to v0.10. Removed excess print lines.

2018-04-06 22:10 UTC, merged